" vim:set ft=vim:

runtime bundles.conf
runtime visual.conf
runtime formatting.conf
runtime mappings.conf

" Miscellaneous
" ------------------------------------------------------------------------------

" don't want any of that
set noswapfile
set nobackup

" case-insensitive search, unless a capital letter is used
set ignorecase
set smartcase

" buffer gets set as hidden when unloaded
set hidden

" ignore DS_Store files
set wildignore+=.DS_Store,*/node_modules/*

" autocomplete
if has("autocmd") && exists("+omnifunc")
  autocmd Filetype *
        \if &omnifunc == "" |
        \setlocal omnifunc=syntaxcomplete#Complete |
        \endif
endif

" handle erb as html
autocmd BufNewFile,BufRead *.erb set filetype=eruby.html

" .snippet is a snippet
autocmd BufNewFile,BufRead *.snippet set filetype=snippet

" mkdir when saving a file in new directories
function! s:MkNonExDir(file, buf)
  if empty(getbufvar(a:buf, '&buftype')) && a:file!~#'\v^\w+\:\/'
    let dir=fnamemodify(a:file, ':h')
    if !isdirectory(dir)
      call mkdir(dir, 'p')
    endif
  endif
endfunction
augroup BWCCreateDir
  autocmd!
  autocmd BufWritePre * :call s:MkNonExDir(expand('<afile>'), +expand('<abuf>'))
augroup END
